name: CI Web

on:
  pull_request:
    branches: [main, develop]

concurrency:
  group: ci-web-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  analyze-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Dependências
        run: flutter pub get

      - name: Analisar
        run: dart analyze lib
